"""initial schema

Revision ID: 311852e10862
Revises:
Create Date: 2026-04-08 11:56:38.427016

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "311852e10862"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_session",
        sa.Column("session_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "entity",
        sa.Column("lei", sa.String(length=20), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("rcs_number", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("jurisdiction", sa.String(length=10), nullable=True),
        sa.Column("nace_code", sa.String(length=10), nullable=True),
        sa.Column("gleif_last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("lei"),
    )
    op.create_table(
        "pipeline_run",
        sa.Column("run_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sources_attempted", sa.JSON(), nullable=False),
        sa.Column("sources_failed", sa.JSON(), nullable=False),
        sa.Column("events_created", sa.Integer(), nullable=False),
        sa.Column("versions_created", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "regulation",
        sa.Column("regulation_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "LU_LAW",
                "CSSF_CIRCULAR",
                "CSSF_REGULATION",
                "EU_REGULATION",
                "EU_DIRECTIVE",
                "ESMA_GUIDELINE",
                "RTS",
                "ITS",
                "DELEGATED_ACT",
                name="regulationtype",
            ),
            nullable=False,
        ),
        sa.Column("reference_number", sa.String(length=100), nullable=False),
        sa.Column("celex_id", sa.String(length=50), nullable=True),
        sa.Column("eli_uri", sa.String(length=500), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("issuing_authority", sa.String(length=100), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column(
            "lifecycle_stage",
            sa.Enum(
                "CONSULTATION",
                "PROPOSAL",
                "DRAFT_BILL",
                "ADOPTED_NOT_IN_FORCE",
                "IN_FORCE",
                "AMENDED",
                "REPEALED",
                name="lifecyclestage",
            ),
            nullable=False,
        ),
        sa.Column("transposition_deadline", sa.Date(), nullable=True),
        sa.Column("application_date", sa.Date(), nullable=True),
        sa.Column("is_ict", sa.Boolean(), nullable=False),
        sa.Column(
            "dora_pillar",
            sa.Enum(
                "ICT_RISK_MGMT",
                "INCIDENT_REPORTING",
                "RESILIENCE_TESTING",
                "THIRD_PARTY_RISK",
                "INFO_SHARING",
                name="dorapillar",
            ),
            nullable=True,
        ),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("source_of_truth", sa.String(length=20), nullable=False),
        sa.Column("replaced_by_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["replaced_by_id"], ["regulation.regulation_id"]),
        sa.PrimaryKeyConstraint("regulation_id"),
    )
    op.create_index(
        op.f("ix_regulation_celex_id"), "regulation", ["celex_id"], unique=False
    )
    op.create_index(
        op.f("ix_regulation_eli_uri"), "regulation", ["eli_uri"], unique=False
    )
    op.create_index(
        op.f("ix_regulation_reference_number"),
        "regulation",
        ["reference_number"],
        unique=False,
    )
    op.create_table(
        "update_event",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_ict", sa.Boolean(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("seen_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_update_event_content_hash"),
        "update_event",
        ["content_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_update_event_published_at"),
        "update_event",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_update_event_review_status"),
        "update_event",
        ["review_status"],
        unique=False,
    )
    op.create_table(
        "authorization",
        sa.Column(
            "authorization_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("lei", sa.String(length=20), nullable=False),
        sa.Column(
            "type",
            sa.Enum("AIFM", "CHAPTER15_MANCO", name="authorizationtype"),
            nullable=False,
        ),
        sa.Column("cssf_entity_id", sa.String(length=20), nullable=True),
        sa.Column("authorization_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("cssf_url", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["lei"], ["entity.lei"]),
        sa.PrimaryKeyConstraint("authorization_id"),
        sa.UniqueConstraint("lei", "type", name="uq_authorization_lei_type"),
    )
    op.create_table(
        "chat_message",
        sa.Column("message_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("retrieved_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["chat_session.session_id"]),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index(
        op.f("ix_chat_message_session_id"),
        "chat_message",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "document_version",
        sa.Column("version_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("regulation_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("html_text", sa.Text(), nullable=True),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("pdf_extracted_text", sa.Text(), nullable=True),
        sa.Column("pdf_is_protected", sa.Boolean(), nullable=False),
        sa.Column("pdf_manual_upload", sa.Boolean(), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["regulation_id"],
            ["regulation.regulation_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint(
            "regulation_id",
            "version_number",
            name="uq_document_version_regulation_version",
        ),
    )
    op.create_index(
        op.f("ix_document_version_content_hash"),
        "document_version",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_version_is_current"),
        "document_version",
        ["is_current"],
        unique=False,
    )
    op.create_index(
        "uq_document_version_one_current",
        "document_version",
        ["regulation_id"],
        unique=True,
        sqlite_where=sa.text("is_current = 1"),
    )
    op.create_table(
        "regulation_alias",
        sa.Column("alias_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("regulation_id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(length=500), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["regulation_id"], ["regulation.regulation_id"]),
        sa.PrimaryKeyConstraint("alias_id"),
    )
    op.create_table(
        "regulation_applicability",
        sa.Column(
            "applicability_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("regulation_id", sa.Integer(), nullable=False),
        sa.Column("authorization_type", sa.String(length=20), nullable=False),
        sa.Column("scope_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["regulation_id"], ["regulation.regulation_id"]),
        sa.PrimaryKeyConstraint("applicability_id"),
    )
    op.create_table(
        "regulation_lifecycle_link",
        sa.Column("link_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_regulation_id", sa.Integer(), nullable=False),
        sa.Column("to_regulation_id", sa.Integer(), nullable=False),
        sa.Column("relation", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_regulation_id"], ["regulation.regulation_id"]
        ),
        sa.ForeignKeyConstraint(
            ["to_regulation_id"], ["regulation.regulation_id"]
        ),
        sa.PrimaryKeyConstraint("link_id"),
    )
    op.create_table(
        "update_event_regulation_link",
        sa.Column("link_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("regulation_id", sa.Integer(), nullable=False),
        sa.Column("match_method", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("matched_snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["update_event.event_id"]),
        sa.ForeignKeyConstraint(
            ["regulation_id"],
            ["regulation.regulation_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("link_id"),
    )
    op.create_table(
        "document_chunk",
        sa.Column("chunk_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("regulation_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("lifecycle_stage", sa.String(length=30), nullable=False),
        sa.Column("is_ict", sa.Boolean(), nullable=False),
        sa.Column("authorization_types", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["regulation_id"],
            ["regulation.regulation_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["document_version.version_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_index(
        op.f("ix_document_chunk_regulation_id"),
        "document_chunk",
        ["regulation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_version_id"),
        "document_chunk",
        ["version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_chunk_version_id"), table_name="document_chunk"
    )
    op.drop_index(
        op.f("ix_document_chunk_regulation_id"), table_name="document_chunk"
    )
    op.drop_table("document_chunk")
    op.drop_table("update_event_regulation_link")
    op.drop_table("regulation_lifecycle_link")
    op.drop_table("regulation_applicability")
    op.drop_table("regulation_alias")
    op.drop_index(
        "uq_document_version_one_current",
        table_name="document_version",
        sqlite_where=sa.text("is_current = 1"),
    )
    op.drop_index(
        op.f("ix_document_version_is_current"), table_name="document_version"
    )
    op.drop_index(
        op.f("ix_document_version_content_hash"), table_name="document_version"
    )
    op.drop_table("document_version")
    op.drop_index(
        op.f("ix_chat_message_session_id"), table_name="chat_message"
    )
    op.drop_table("chat_message")
    op.drop_table("authorization")
    op.drop_index(
        op.f("ix_update_event_review_status"), table_name="update_event"
    )
    op.drop_index(
        op.f("ix_update_event_published_at"), table_name="update_event"
    )
    op.drop_index(
        op.f("ix_update_event_content_hash"), table_name="update_event"
    )
    op.drop_table("update_event")
    op.drop_index(
        op.f("ix_regulation_reference_number"), table_name="regulation"
    )
    op.drop_index(op.f("ix_regulation_eli_uri"), table_name="regulation")
    op.drop_index(op.f("ix_regulation_celex_id"), table_name="regulation")
    op.drop_table("regulation")
    op.drop_table("pipeline_run")
    op.drop_table("entity")
    op.drop_table("chat_session")
    # ### end Alembic commands ###
